10 - Fix asset exchange rate
OpenFuturePlatform/open-api pull request #13
Opened 2020-12-11 13:05 UTC by layko-andrey

Changed exchange rates API URL to Binance API

2020-12-11 14:44 UTC, trenatov requested changes

2020-12-11 14:44 UTC, trenatov commented on frontend/src/actions/deploy-contract.js
> +    return data.price *fromAmount;
space after * ?

2020-12-14 19:28 UTC, ruslanys reviewed
By the way, did we test locally how it works?

2020-12-14 19:28 UTC, ruslanys commented on frontend/src/actions/deploy-contract.js
> +    return data.price *fromAmount;
Yes, space is missing.

2020-12-14 19:28 UTC, ruslanys requested changes
Need to resolve comments

2021-03-09 09:45 UTC, merged