Copyright script
OpenFuturePlatform/open-api pull request #16
Opened 2021-02-08 14:43 UTC by trenatov

2021-02-08 20:44 UTC, ruslanys commented on docker/Dockerfile
> +FROM openjdk:12.0.2-jdk-oracle
we use lts jdks only

2021-02-08 20:46 UTC, ruslanys requested changes

2021-02-08 20:46 UTC, ruslanys commented on build.gradle
> +version = 'v2.6.9'   //versionDetails().lastTag[1..-1] + (versionDetails().isCleanTag ? '' : '-DIRTY')
use `id 'io.zensoft.versioning' version '1.1.0'` plugin instead

2021-02-08 20:46 UTC, ruslanys commented on docker/Dockerfile
> +FROM openjdk:12.0.2-jdk-oracle
we use lts jdks only, switch to 11.

Also we do not use proprietary Oracle builds.

2021-02-11 09:28 UTC, trenatov commented
Will be created from master branch

2021-02-11 09:28 UTC, closed without merging